# =============================================
# dbt_project.yml - Corrected Version
# =============================================

name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# =============================================
# Models Configuration
# =============================================
models:
  jaffle_shop:
    +materialized: ephemeral

# =============================================
# Seeds Configuration
# =============================================
seeds:
  jaffle_shop:
    country_codes:
      +enabled: true
      +schema: lookup
      +alias: country_lookup
      +header: true
      +quote_columns: false
      +column_types:
        country_code: string
        country_name: string
